"""
OMNICUS AI Brain Module
=======================
The central decision engine that powers OMNICUS's trading intelligence.

This module integrates all cognitive components:
- Memory Bank for experience
- Emotion Tracker for instincts
- Skill Registry for abilities
- ToolKit for instruments
- Workflow Engine for orchestration

Together they form OMNICUS's "brain" - a human-like trading mind.
"""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any, Tuple
from enum import Enum
import asyncio
import json
import statistics
from decimal import Decimal

# Import sibling modules
from .memory_bank import MemoryBank, Memory, MemoryType
from .emotions import EmotionTracker, EmotionalState, PersonalityConfig
from .skills import SkillRegistry, SkillCategory, SkillLevel
from .tools import ToolKit, ToolType, ToolResult
from .workflow import WorkflowEngine, WorkflowType, Workflow


class DecisionType(Enum):
    """Types of trading decisions"""
    ENTER_LONG = "enter_long"
    ENTER_SHORT = "enter_short"
    EXIT_POSITION = "exit_position"
    HOLD_POSITION = "hold_position"
    ADJUST_STOP = "adjust_stop"
    SCALE_IN = "scale_in"
    SCALE_OUT = "scale_out"
    NO_ACTION = "no_action"


class ConfidenceLevel(Enum):
    """Confidence levels for decisions"""
    VERY_LOW = 1
    LOW = 2
    MODERATE = 3
    HIGH = 4
    VERY_HIGH = 5


@dataclass
class MarketContext:
    """Current market context for decision making"""
    
    symbol: str
    current_price: float
    timestamp: datetime = field(default_factory=datetime.now)
    
    # Price data
    prices: List[float] = field(default_factory=list)
    volumes: List[float] = field(default_factory=list)
    highs: List[float] = field(default_factory=list)
    lows: List[float] = field(default_factory=list)
    
    # Technical indicators
    indicators: Dict[str, float] = field(default_factory=dict)
    
    # Market state
    volatility: float = 0.0
    trend: str = "neutral"  # bullish, bearish, neutral
    momentum: str = "neutral"  # strong_up, up, neutral, down, strong_down
    
    # Sentiment
    sentiment_score: float = 0.5
    news_sentiment: float = 0.5
    social_sentiment: float = 0.5
    
    # Additional data
    market_cap: Optional[float] = None
    volume_24h: Optional[float] = None
    price_change_24h: Optional[float] = None
    
    def to_dict(self) -> Dict:
        return {
            "symbol": self.symbol,
            "current_price": self.current_price,
            "timestamp": self.timestamp.isoformat(),
            "trend": self.trend,
            "momentum": self.momentum,
            "volatility": round(self.volatility, 4),
            "sentiment": round(self.sentiment_score, 3),
        }


@dataclass
class TradeSignal:
    """A trading signal generated by the AI Brain"""
    
    symbol: str
    action: DecisionType
    confidence: float
    reasoning: str
    
    # Trade parameters
    suggested_entry: Optional[float] = None
    suggested_stop: Optional[float] = None
    suggested_target: Optional[float] = None
    position_size_percent: float = 2.0
    
    # Signal metadata
    signal_strength: float = 0.5
    risk_reward_ratio: float = 2.0
    expected_holding_time: str = "hours"  # minutes, hours, days, weeks
    
    # Factor breakdown
    factors: Dict[str, float] = field(default_factory=dict)
    
    # Related memories
    relevant_memories: List[str] = field(default_factory=list)
    
    # Timestamp
    created_at: datetime = field(default_factory=datetime.now)
    
    def to_dict(self) -> Dict:
        return {
            "symbol": self.symbol,
            "action": self.action.value,
            "confidence": round(self.confidence, 3),
            "reasoning": self.reasoning,
            "suggested_entry": self.suggested_entry,
            "suggested_stop": self.suggested_stop,
            "suggested_target": self.suggested_target,
            "position_size_percent": self.position_size_percent,
            "signal_strength": round(self.signal_strength, 3),
            "risk_reward_ratio": self.risk_reward_ratio,
            "factors": {k: round(v, 3) for k, v in self.factors.items()},
            "created_at": self.created_at.isoformat(),
        }


@dataclass
class AnalysisResult:
    """Result of market analysis"""
    
    symbol: str
    timestamp: datetime = field(default_factory=datetime.now)
    
    # Technical analysis
    technical_score: float = 0.5
    technical_signals: List[str] = field(default_factory=list)
    
    # Pattern analysis
    pattern_score: float = 0.5
    patterns_detected: List[str] = field(default_factory=list)
    
    # Sentiment analysis
    sentiment_score: float = 0.5
    sentiment_signals: List[str] = field(default_factory=list)
    
    # Risk assessment
    risk_score: float = 0.5
    risk_factors: List[str] = field(default_factory=list)
    
    # Overall
    overall_score: float = 0.5
    recommendation: str = "hold"
    
    def to_dict(self) -> Dict:
        return {
            "symbol": self.symbol,
            "timestamp": self.timestamp.isoformat(),
            "technical_score": round(self.technical_score, 3),
            "pattern_score": round(self.pattern_score, 3),
            "sentiment_score": round(self.sentiment_score, 3),
            "risk_score": round(self.risk_score, 3),
            "overall_score": round(self.overall_score, 3),
            "recommendation": self.recommendation,
            "signals": {
                "technical": self.technical_signals,
                "patterns": self.patterns_detected,
                "sentiment": self.sentiment_signals,
                "risk": self.risk_factors,
            }
        }


class AIBrain:
    """
    OMNICUS's Central Decision Engine
    
    The AI Brain is where all cognitive components come together to make
    trading decisions. It integrates:
    
    - **Memory**: Past experiences shape current decisions
    - **Emotions**: Instincts and confidence affect risk tolerance
    - **Skills**: Trained abilities improve accuracy
    - **Tools**: Practical instruments for analysis
    - **Workflows**: Structured decision processes
    
    The Brain generates TradeSignals with full reasoning and confidence,
    always learning and adapting from outcomes.
    """
    
    def __init__(
        self,
        memory_bank: MemoryBank = None,
        emotion_tracker: EmotionTracker = None,
        skill_registry: SkillRegistry = None,
        toolkit: ToolKit = None,
        workflow_engine: WorkflowEngine = None,
        personality: PersonalityConfig = None
    ):
        """
        Initialize the AI Brain
        
        Args:
            memory_bank: Memory storage (creates new if None)
            emotion_tracker: Emotional state tracker (creates new if None)
            skill_registry: Skills registry (creates new if None)
            toolkit: Trading tools (creates new if None)
            workflow_engine: Workflow orchestrator (creates new if None)
            personality: Personality configuration
        """
        # Initialize cognitive components
        self.memory = memory_bank or MemoryBank()
        self.emotions = emotion_tracker or EmotionTracker(personality)
        self.skills = skill_registry or SkillRegistry()
        self.tools = toolkit or ToolKit()
        self.workflows = workflow_engine or WorkflowEngine()
        
        # Decision configuration
        self.min_confidence_threshold = 0.60
        self.max_position_size_percent = 5.0
        self.risk_per_trade_percent = 2.0
        
        # Analysis weights
        self.analysis_weights = {
            "technical": 0.30,
            "pattern": 0.20,
            "sentiment": 0.15,
            "momentum": 0.15,
            "risk": 0.10,
            "memory": 0.10,
        }
        
        # Session tracking
        self._analysis_count = 0
        self._decision_count = 0
        self._last_analysis: Optional[datetime] = None
    
    async def analyze_market(self, context: MarketContext) -> AnalysisResult:
        """
        Perform comprehensive market analysis
        
        Args:
            context: Current market context
            
        Returns:
            AnalysisResult with all analysis components
        """
        self._analysis_count += 1
        self._last_analysis = datetime.now()
        
        result = AnalysisResult(symbol=context.symbol)
        
        # 1. Technical Analysis
        result.technical_score = await self._analyze_technical(context)
        result.technical_signals = self._get_technical_signals(context)
        
        # 2. Pattern Recognition
        pattern_result = await self.tools.use_tool(
            "pattern_recognition",
            prices=context.prices,
            volumes=context.volumes
        )
        if pattern_result.success and pattern_result.data:
            patterns = pattern_result.data.get("patterns", [])
            result.patterns_detected = [p["pattern"] for p in patterns]
            bullish_patterns = sum(1 for p in patterns if p.get("implication") == "bullish")
            bearish_patterns = sum(1 for p in patterns if p.get("implication") == "bearish")
            total = max(1, len(patterns))
            result.pattern_score = 0.5 + (bullish_patterns - bearish_patterns) / (total * 2)
        
        # 3. Sentiment Analysis
        result.sentiment_score = self._analyze_sentiment(context)
        result.sentiment_signals = self._get_sentiment_signals(context)
        
        # 4. Risk Assessment
        result.risk_score = self._assess_risk(context)
        result.risk_factors = self._get_risk_factors(context)
        
        # 5. Memory Influence
        memory_influence = self._get_memory_influence(context)
        
        # 6. Calculate overall score
        result.overall_score = self._calculate_overall_score(
            technical=result.technical_score,
            pattern=result.pattern_score,
            sentiment=result.sentiment_score,
            risk=result.risk_score,
            memory=memory_influence,
            context=context
        )
        
        # 7. Generate recommendation
        result.recommendation = self._generate_recommendation(result.overall_score, context)
        
        return result
    
    async def _analyze_technical(self, context: MarketContext) -> float:
        """Perform technical analysis using skills and tools"""
        
        # Use technical indicator tool
        if len(context.prices) >= 20:
            indicator_result = await self.tools.use_tool(
                "technical_indicators",
                prices=context.prices,
                indicators=["sma", "ema", "rsi", "macd"]
            )
            
            if indicator_result.success and indicator_result.data:
                indicators = indicator_result.data
                score = 0.5
                
                # RSI analysis
                rsi = indicators.get("rsi")
                if rsi:
                    if rsi < 30:
                        score += 0.15  # Oversold - bullish
                        self.skills.use_skill("technical_analysis", True, 0.1)
                    elif rsi > 70:
                        score -= 0.15  # Overbought - bearish
                        self.skills.use_skill("technical_analysis", True, 0.1)
                    self.skills.use_skill("technical_analysis", True)
                
                # MACD analysis
                macd = indicators.get("macd")
                signal = indicators.get("macd_signal")
                if macd and signal:
                    if macd > signal:
                        score += 0.10  # Bullish MACD
                    else:
                        score -= 0.10  # Bearish MACD
                
                # Moving average analysis
                sma_20 = indicators.get("sma_20")
                current_price = context.current_price
                if sma_20:
                    if current_price > sma_20:
                        score += 0.10  # Above MA - bullish
                    else:
                        score -= 0.10  # Below MA - bearish
                
                # Trend influence
                if context.trend == "bullish":
                    score += 0.10
                elif context.trend == "bearish":
                    score -= 0.10
                
                return max(0.1, min(0.9, score))
        
        # Default if no data
        return 0.5
    
    def _get_technical_signals(self, context: MarketContext) -> List[str]:
        """Extract technical signals from context"""
        signals = []
        
        if context.indicators:
            rsi = context.indicators.get("rsi")
            if rsi:
                if rsi < 30:
                    signals.append("RSI oversold")
                elif rsi > 70:
                    signals.append("RSI overbought")
            
            macd = context.indicators.get("macd")
            if macd and macd > 0:
                signals.append("MACD positive")
            elif macd and macd < 0:
                signals.append("MACD negative")
        
        if context.trend == "bullish":
            signals.append("Uptrend")
        elif context.trend == "bearish":
            signals.append("Downtrend")
        
        if context.momentum in ["strong_up", "up"]:
            signals.append("Bullish momentum")
        elif context.momentum in ["strong_down", "down"]:
            signals.append("Bearish momentum")
        
        return signals
    
    def _analyze_sentiment(self, context: MarketContext) -> float:
        """Analyze market sentiment"""
        score = 0.5
        
        # Weight sentiment sources
        score = (
            context.sentiment_score * 0.4 +
            context.news_sentiment * 0.35 +
            context.social_sentiment * 0.25
        )
        
        # Update sentiment skill
        self.skills.use_skill("sentiment_analysis", True)
        
        return score
    
    def _get_sentiment_signals(self, context: MarketContext) -> List[str]:
        """Extract sentiment signals"""
        signals = []
        
        if context.sentiment_score > 0.6:
            signals.append("Positive market sentiment")
        elif context.sentiment_score < 0.4:
            signals.append("Negative market sentiment")
        
        if context.news_sentiment > 0.65:
            signals.append("Bullish news")
        elif context.news_sentiment < 0.35:
            signals.append("Bearish news")
        
        return signals
    
    def _assess_risk(self, context: MarketContext) -> float:
        """Assess risk level (higher = more risky, lower score = avoid)"""
        
        # Start with neutral
        risk_score = 0.5
        
        # High volatility increases risk
        if context.volatility > 0.05:  # 5%+ daily volatility
            risk_score += 0.15
        elif context.volatility > 0.03:
            risk_score += 0.08
        
        # Extreme price changes
        if context.price_change_24h:
            if abs(context.price_change_24h) > 10:
                risk_score += 0.15
            elif abs(context.price_change_24h) > 5:
                risk_score += 0.08
        
        # Trend against momentum = risky
        if context.trend == "bullish" and context.momentum in ["down", "strong_down"]:
            risk_score += 0.10
        elif context.trend == "bearish" and context.momentum in ["up", "strong_up"]:
            risk_score += 0.10
        
        # Update risk skill
        self.skills.use_skill("risk_assessment", True)
        
        return min(1.0, risk_score)
    
    def _get_risk_factors(self, context: MarketContext) -> List[str]:
        """Identify risk factors"""
        factors = []
        
        if context.volatility > 0.05:
            factors.append("High volatility")
        
        if context.price_change_24h and abs(context.price_change_24h) > 10:
            factors.append("Extreme price movement")
        
        if context.trend == "neutral":
            factors.append("Unclear trend direction")
        
        # Check emotional state
        if self.emotions.should_reduce_risk():
            factors.append("Emotional state suggests caution")
        
        return factors
    
    def _get_memory_influence(self, context: MarketContext) -> float:
        """Get influence from past experiences"""
        
        # Recall similar situations
        memories = self.memory.recall_similar_situations(
            symbol=context.symbol,
            current_conditions={"trend": context.trend}
        )
        
        if not memories:
            return 0.5  # Neutral if no experience
        
        # Calculate influence from memories
        wins = sum(1 for m in memories if m.actual_outcome == "win")
        losses = sum(1 for m in memories if m.actual_outcome == "loss")
        total = len(memories)
        
        if total == 0:
            return 0.5
        
        # Win rate influence
        win_rate = wins / total
        
        # Adjust based on memory importance
        weighted_score = sum(
            (1 if m.actual_outcome == "win" else 0) * m.importance
            for m in memories
        ) / sum(m.importance for m in memories)
        
        return weighted_score
    
    def _calculate_overall_score(
        self,
        technical: float,
        pattern: float,
        sentiment: float,
        risk: float,
        memory: float,
        context: MarketContext
    ) -> float:
        """Calculate weighted overall score"""
        
        # Base score from weighted components
        score = (
            technical * self.analysis_weights["technical"] +
            pattern * self.analysis_weights["pattern"] +
            sentiment * self.analysis_weights["sentiment"] +
            memory * self.analysis_weights["memory"]
        )
        
        # Risk adjustment (high risk reduces score)
        risk_adjustment = 1.0 - (risk * 0.3)  # Up to 30% reduction
        score *= risk_adjustment
        
        # Emotional state adjustment
        confidence_adj = self.emotions.get_confidence_adjustment()
        score *= confidence_adj
        
        # Skill accuracy influence
        relevant_skills = self.skills.get_skills_for_trade("trend_follow")
        if relevant_skills:
            skill_accuracy = self.skills.calculate_combined_accuracy(
                [s.name for s in relevant_skills]
            )
            # Blend with skill accuracy
            score = score * 0.7 + skill_accuracy * 0.3
        
        return max(0.1, min(0.95, score))
    
    def _generate_recommendation(self, score: float, context: MarketContext) -> str:
        """Generate trading recommendation"""
        
        if score >= 0.75:
            return "strong_buy"
        elif score >= 0.65:
            return "buy"
        elif score >= 0.55:
            return "hold_bullish"
        elif score >= 0.45:
            return "hold"
        elif score >= 0.35:
            return "hold_bearish"
        elif score >= 0.25:
            return "sell"
        else:
            return "strong_sell"
    
    async def generate_signal(
        self,
        context: MarketContext,
        analysis: AnalysisResult = None
    ) -> TradeSignal:
        """
        Generate a trading signal
        
        Args:
            context: Market context
            analysis: Pre-computed analysis (will compute if None)
            
        Returns:
            TradeSignal with decision and reasoning
        """
        self._decision_count += 1
        
        # Get analysis if not provided
        if analysis is None:
            analysis = await self.analyze_market(context)
        
        # Determine action
        action = self._determine_action(analysis, context)
        
        # Calculate confidence
        confidence = self._calculate_confidence(analysis, context)
        
        # Generate reasoning
        reasoning = self._generate_reasoning(analysis, context, action)
        
        # Create signal
        signal = TradeSignal(
            symbol=context.symbol,
            action=action,
            confidence=confidence,
            reasoning=reasoning,
            factors={
                "technical": analysis.technical_score,
                "pattern": analysis.pattern_score,
                "sentiment": analysis.sentiment_score,
                "risk": analysis.risk_score,
            }
        )
        
        # Calculate trade parameters
        if action in [DecisionType.ENTER_LONG, DecisionType.ENTER_SHORT]:
            signal = await self._calculate_trade_parameters(signal, context, analysis)
        
        # Check if confidence meets threshold
        if confidence < self.min_confidence_threshold:
            signal.action = DecisionType.NO_ACTION
            signal.reasoning = f"Confidence ({confidence:.2f}) below threshold ({self.min_confidence_threshold}). " + signal.reasoning
        
        # Add relevant memories
        memories = self.memory.recall_similar_situations(
            symbol=context.symbol,
            current_conditions={"trend": context.trend}
        )
        signal.relevant_memories = [m.what_i_learned for m in memories[:3]]
        
        return signal
    
    def _determine_action(
        self, 
        analysis: AnalysisResult, 
        context: MarketContext
    ) -> DecisionType:
        """Determine trading action"""
        
        score = analysis.overall_score
        
        # Check emotional state
        should_pause, pause_reason = self.emotions.should_pause_trading()
        if should_pause:
            return DecisionType.NO_ACTION
        
        # Check risk
        if analysis.risk_score > 0.8:
            return DecisionType.NO_ACTION
        
        # Determine action based on score
        if score >= 0.70:
            return DecisionType.ENTER_LONG
        elif score >= 0.60:
            return DecisionType.ENTER_LONG  # Still bullish
        elif score <= 0.30:
            return DecisionType.ENTER_SHORT
        elif score <= 0.40:
            return DecisionType.ENTER_SHORT  # Still bearish
        
        return DecisionType.NO_ACTION
    
    def _calculate_confidence(
        self,
        analysis: AnalysisResult,
        context: MarketContext
    ) -> float:
        """Calculate confidence for the signal"""
        
        # Base confidence from analysis
        base_confidence = abs(analysis.overall_score - 0.5) * 2  # 0 to 1
        
        # Factor agreement
        scores = [
            analysis.technical_score,
            analysis.pattern_score,
            analysis.sentiment_score,
        ]
        agreement = 1.0 - statistics.stdev(scores) if len(scores) > 1 else 0.5
        
        # Combine
        confidence = base_confidence * 0.6 + agreement * 0.4
        
        # Emotional state influence
        confidence *= self.emotions.get_confidence_adjustment()
        
        # Skill confidence
        skills = self.skills.get_top_skills(3)
        if skills:
            avg_skill_accuracy = sum(s.current_accuracy for s in skills) / len(skills)
            confidence = confidence * 0.7 + avg_skill_accuracy * 0.3
        
        return min(0.95, max(0.1, confidence))
    
    def _generate_reasoning(
        self,
        analysis: AnalysisResult,
        context: MarketContext,
        action: DecisionType
    ) -> str:
        """Generate human-readable reasoning"""
        
        parts = []
        
        # Action summary
        action_phrases = {
            DecisionType.ENTER_LONG: "Bullish setup detected. ",
            DecisionType.ENTER_SHORT: "Bearish setup detected. ",
            DecisionType.EXIT_POSITION: "Exiting position. ",
            DecisionType.HOLD_POSITION: "Holding current position. ",
            DecisionType.NO_ACTION: "No clear signal. ",
        }
        parts.append(action_phrases.get(action, "Analyzing. "))
        
        # Technical reasons
        if analysis.technical_signals:
            parts.append(f"Technical: {', '.join(analysis.technical_signals[:3])}. ")
        
        # Pattern reasons
        if analysis.patterns_detected:
            parts.append(f"Patterns: {', '.join(analysis.patterns_detected[:2])}. ")
        
        # Sentiment
        if analysis.sentiment_signals:
            parts.append(f"Sentiment: {', '.join(analysis.sentiment_signals[:2])}. ")
        
        # Risk note
        if analysis.risk_factors:
            parts.append(f"Risks: {', '.join(analysis.risk_factors[:2])}. ")
        
        # Emotional state
        emotional_state = self.emotions.get_emotional_summary()
        parts.append(f"State: {emotional_state}")
        
        return "".join(parts)
    
    async def _calculate_trade_parameters(
        self,
        signal: TradeSignal,
        context: MarketContext,
        analysis: AnalysisResult
    ) -> TradeSignal:
        """Calculate entry, stop, target, and position size"""
        
        # Entry price
        signal.suggested_entry = context.current_price
        
        # Stop loss calculation
        stop_result = await self.tools.use_tool(
            "stop_loss_calculator",
            entry_price=context.current_price,
            method="percentage",
            risk_percent=2.0
        )
        
        if stop_result.success and stop_result.data:
            signal.suggested_stop = stop_result.data["stop_loss_price"]
        
        # Position sizing
        position_result = await self.tools.use_tool(
            "position_sizer",
            capital=10000,  # Would be actual capital
            risk_percent=self.risk_per_trade_percent,
            entry_price=context.current_price,
            stop_loss_price=signal.suggested_stop or context.current_price * 0.98
        )
        
        if position_result.success and position_result.data:
            signal.position_size_percent = position_result.data["capital_used_percent"]
        
        # Target (based on risk-reward)
        if signal.suggested_stop:
            risk_amount = abs(signal.suggested_entry - signal.suggested_stop)
            signal.suggested_target = signal.suggested_entry + (risk_amount * signal.risk_reward_ratio)
        
        # Adjust for emotional state
        risk_tolerance = self.emotions.get_risk_tolerance()
        signal.position_size_percent *= risk_tolerance
        signal.position_size_percent = min(
            signal.position_size_percent,
            self.max_position_size_percent
        )
        
        return signal
    
    async def learn_from_outcome(
        self,
        signal: TradeSignal,
        outcome_pnl: float,
        outcome_type: str,  # "win", "loss", "breakeven"
        hold_duration: float = 0,  # hours
        exit_reason: str = ""
    ):
        """
        Learn from a trade outcome
        
        Args:
            signal: The original trade signal
            outcome_pnl: Profit or loss amount
            outcome_type: Outcome classification
            hold_duration: How long position was held
            exit_reason: Why the trade was closed
        """
        was_win = outcome_type == "win"
        
        # Update skills
        skill_names = ["technical_analysis", "risk_assessment", "entry_timing"]
        for skill_name in skill_names:
            self.skills.use_skill(skill_name, was_win, outcome_pnl)
        
        # Update emotional state
        self.emotions.update_from_trade(
            pnl=outcome_pnl,
            confidence=signal.confidence,
            was_win=was_win
        )
        
        # Create memory
        if was_win:
            self.memory.create_victory_memory(
                symbol=signal.symbol,
                trade_id=signal.created_at.strftime("%Y%m%d%H%M%S"),
                profit=outcome_pnl,
                reasoning=signal.reasoning,
                confidence=signal.confidence
            )
        else:
            self.memory.create_mistake_memory(
                symbol=signal.symbol,
                trade_id=signal.created_at.strftime("%Y%m%d%H%M%S"),
                loss=outcome_pnl,
                reasoning=signal.reasoning,
                confidence=signal.confidence,
                mistake_type=exit_reason or "unknown"
            )
        
        # Record pattern
        if signal.factors:
            for factor, score in signal.factors.items():
                if score > 0.7:
                    self.memory.record_pattern(f"high_{factor}_success")
    
    def get_brain_state(self) -> Dict:
        """
        Get complete brain state for dashboard
        
        Returns:
            Dictionary with all brain components' state
        """
        return {
            "session_stats": {
                "analyses_performed": self._analysis_count,
                "decisions_made": self._decision_count,
                "last_analysis": self._last_analysis.isoformat() if self._last_analysis else None,
            },
            "emotional_state": self.emotions.get_state(),
            "memory_stats": self.memory.get_memory_stats(),
            "skill_stats": self.skills.get_registry_stats(),
            "toolkit_stats": self.tools.get_toolkit_stats(),
            "workflow_stats": self.workflows.get_workflow_stats(),
            "configuration": {
                "min_confidence": self.min_confidence_threshold,
                "max_position_percent": self.max_position_size_percent,
                "risk_per_trade": self.risk_per_trade_percent,
            }
        }
    
    def set_confidence_threshold(self, threshold: float):
        """Set minimum confidence threshold for trading"""
        self.min_confidence_threshold = max(0.5, min(0.9, threshold))
    
    def set_risk_parameters(self, max_position: float, risk_per_trade: float):
        """Set risk management parameters"""
        self.max_position_size_percent = max(1.0, min(10.0, max_position))
        self.risk_per_trade_percent = max(0.5, min(5.0, risk_per_trade))


# Default AI Brain instance
ai_brain = AIBrain()
